Dst: ne30np4
DstVgrid: L93
IC_for_pg: true
Output_base_dir: /glade/derecho/scratch/juliob/rough_topo_ICs_c202506/
Override_topofile_with: /glade/campaign/cgd/amp/pel/topo/cesm3/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0050_noleak_20250325.nc
Resubmit: 743
StepBy: month
StepN: 3
TheProcYear: -1
day: 1
frequency: 6
hour: 0
month: 6
mpas_nudging: false
year: 2000
